CREATE TABLE credit_card_details (
    sno INT PRIMARY KEY,
    label INT,
    id INT NOT NULL UNIQUE,
    fea_1 INT,
    fea_2 FLOAT,
    fea_3 INT,
    fea_4 INT,
    fea_5 INT,
    fea_6 INT,
    fea_7 INT,
    fea_8 INT,
    fea_9 INT,
    fea_10 INT,
    fea_11 INT,
    OVD_t1 INT,
    OVD_t2 INT,
    OVD_t3 INT,
    OVD_sum INT,
    pay_normal INT,
    prod_code INT,
    prod_limit FLOAT,
    update_date DATE,
    new_balance FLOAT,
    highest_balance INT,
    report_date DATE
);
